### ISSUE TITLE
"Initializing SDL failed"

### ISSUE THREAD

**Issue by RubenKelevra** [simonwunderlich/FFT_eval#3]
> [ruben@bragi FFT_eval]$ ./fft_eval ../fft_14-09-12T22-37 
> WARNING: Experimental Software! Don't trust anything you see. :)
> 
> read 113 scan results
> Initializing SDL failed
> Failed to initialize graphics.

Compiled under arch-linux with kernel 3.15.8, gcc 4.9.1 and sdl 1.2.15-6

**Comment by RubenKelevra** [comment]
@simonwunderlich is this fixed? 🤔

**Comment by simonwunderlich** [comment]
it works for me [tm]. Actually it always did. But this is an ancient version specified in this ticket, so I was just closing it.

If you want you can test it again ....

**Comment by RubenKelevra** [comment]
@simonwunderlich I'm still wondering what I was doing with this software 🤔
